### ISSUE TITLE
Aparece somente a tabela

### ISSUE THREAD

**Issue by vissoci** [franciscoprado/magentoprecoparcelado#2]
@franciscoprado na loja que estou testando só aparece a tabela.
Eu não entendi o que precisa ser feito para funcionar a frase "ou em {parcelas} vezes de {preco}".

Eu apenas colei o código indicado abaixo de:
`$_product = $this->getProduct();`

Precisa ser feito algo a mais para aparecer a frase do parcelamento?

**Comment by vissoci** [comment]
Só pra avisar quem está tentando fazer algo com esse módulo: tem que fazer muita coisa!!!!
Não basta instalar somente.

**Comment by franciscoprado** [comment]
Olá @apzeiro ,

Sim, de fato sem precisar da parte do preço de forma parcelada ele adiciona sozinho uma tabela com as parcelas. O recurso de preço em parcelas "ou em {parcelas} vezes de {preco}" é para exibir o preço no estilo "ou em 12x de R$ 10,00" por exemplo.

A comunidade aqui está praticamente inativa, recomendo notificar via meu blog ou email do Magento Connect. []s

**Comment by vissoci** [comment]
@franciscoprado Você está respondendo no blog?
Fiz diversas perguntas lá e não tive retorno. Seu módulo é muito interessante e merecia uma atenção maior, pois resolve o problema de muita gente.

O problema é que está pouco documentado e não é plug and play como muitos pensam. Tem modificar bastante coisa pra ficar a contento.

Se quisesse reaquecer o github eu fico a disposição para ajudar.
